api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make   : ~
env_prep   : get-composer
env_post   : ci-coveralls,ci-codacy
php_conf   : timezone
php_exts   : igbinary
app_prep   : dep-composer
app_post   : ~
app_path   : ~
pkg_name   : wonka-library
pkg_desc   : "a collection of framework-agnostic classes, interfaces, traits, and root-namespace functions used as the building blocks for other projects."
