api_branch : origin/master
api_parser : ~
api_cfgmod : clone
api_runner : ~
api_paths  : lib
env_make : ~
env_prep : composer-update
env_post : coveralls,codacy
php_conf : timezone
php_exts : igbinary
app_prep : install-deps
app_post : ~
app_path : ~