---

sudo : false

language : php

php :
  - 5.6
  - 7.0
  - hhvm

matrix :
  fast_finish    : true
  allow_failures :
    - php : hhvm

env :
  global :
    - build_package : true

addons:
  apt:
    packages:
      - gnutls-bin

git :
  depth : 3

before_install :
  - dpkg -l | grep curl
  - curl --version
  - dpkg -l | grep git
  - git --version
  - dpkg -l | grep gnu | grep tls
  - gnutls-cli -V -p 443 src.run
  - gnutls-cli -v
  - git clone --depth=1 --branch=master https://src.run/php/build-knowledge-shared.git config

install :
  - bash config/builders/build-reqs/build-reqs.bash up-env
  - bash config/builders/build-reqs/build-reqs.bash up-app

script :
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script :
  - bash config/builders/build-reqs/build-reqs.bash dn-app
  - bash config/builders/build-reqs/build-reqs.bash dn-env

...
