---

language: php

php:
  - 5.6
  - 7.0

env:
  - scribe_packaged: .scribe-package.yml

before_install:
  - git clone -b master https://src.run/php-libs/build-knowledge-shared.git config

install:
  - bash config/builders/build-reqs/build-reqs.bash up
  - composer install -n || composer update -n

script:
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script:
  - bash config/builders/build-reqs/build-reqs.bash down

...
