---

sudo : false

language : php

php :
  - 5.6
  - 7.0
  - hhvm

matrix :
  fast_finish    : true
  allow_failures :
    - php : hhvm

env :
  global :
    - build_package : true

git :
  depth : 3

cache :
  directories :
    - $TRAVIS_BUILD_DIR/vendor

before_install :
  - git clone https://github.com/scr-be/build-knowledge-shared.git config

install :
  - bash config/builders/build-reqs/build-reqs.bash up-php
  - bash config/builders/build-reqs/build-reqs.bash up-app

script :
  - bin/phpunit --verbose --configuration phpunit.xml.dist

after_script :
  - bash config/builders/build-reqs/build-reqs.bash dn-app
  - bash config/builders/build-reqs/build-reqs.bash dn-php

...
