<?php

/*
 * This file is part of the `src-run/wonka-library` project.
 *
 * (c) Rob Frawley 2nd <rmf@src.run>
 *
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace SR\Wonka\Security\Random;

use SR\Exception\Logic\InvalidArgumentException;

abstract class AbstractGenerator implements GeneratorInterface
{
    /**
     * @var int
     */
    protected $length;

    /**
     * @var bool
     */
    protected $returnFilter;

    /**
     * Set the length of the random bytes to generate.
     *
     * @param $length
     *
     * @throws InvalidArgumentException
     *
     * @return BytesGeneratorInterface
     */
    public function setLength(int $length) : GeneratorInterface
    {
        if ($length < 1) {
            throw new InvalidArgumentException('Cannot generate random bytes with length of "%d" as positive value required.', $length);
        }

        $this->length = $length;

        return $this;
    }

    /**
     * Set closure to call on generated bytes prior to returning the value.
     *
     * @param \Closure|null $returnFilter
     *
     * @return BytesGeneratorInterface
     */
    public function setReturnFilter(\Closure $returnFilter = null) : GeneratorInterface
    {
        $this->returnFilter = $returnFilter;

        return $this;
    }
}

/* EOF */
